### ISSUE TITLE
Use Github Runner to automatically pull the latest image from Dockerhub to Daniel's server

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/nycmesh-support-bot#14]
Depends on #10

**Comment by andybaumgar** [comment]
@danielhmetro Is it OK if I SSH in to your server and install the runner, or would you like to be part of that?

**Comment by andybaumgar** [comment]
Got the runner running on [self-hosted, daniel-server].  I'll explore the Docker workflow tomorrow.
