### ISSUE TITLE
Create a standardized environment variable configuration file

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/nycmesh-support-bot#16]
Create a `.env` file template in `README.md` and migrate existing configuration systems to this file

**Comment by andybaumgar** [comment]
@Andrew-Dickinson Here is how I am currently loading the environment.  I do it globally when my module is imported.
```
from dotenv import load_dotenv
load_dotenv()
```

Do you have a preference for 1 .env file or many?  I think the Python dotenv package should be able to find a global one at the root of our project if we wanted to combine them all.

**Comment by Andrew-Dickinson** [comment]
I'd say let's combine them
