### ISSUE TITLE
Bug: The support bot can be triggered indefinitely for a message thread using the shortcut

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/nycmesh-support-bot#30]
Query Slack's message APIs to check if the supportbot has already participated in the thread before sending content. This will ensure that the support bot can only be triggered once per thread.

**Comment by danielhmetro** [comment]
I think this is a non issue. As long as it's the shortcut and not some automatic detection of the use of a word, it is helpful to rerun the diagnostics once a solution has been found/implemented to make sure that we are seeing the desired metrics post-resolution.
