### ISSUE TITLE
Suggest supportbot when message is posted (prototype)

### ISSUE THREAD

**Issue by andybaumgar** [nycmeshnet/nycmesh-support-bot#47]

**Comment by Andrew-Dickinson** [comment]
We can do this with a "whisper", which send the message only to the member
if we don't want to ping the whole thread

**Comment by andybaumgar** [comment]
Yeah that's a good idea.  I think the idea with this is to run as soon as they post, so they will likely be the only one in thread initially, but maybe a whisper also doesn't show up for others?

**Comment by Andrew-Dickinson** [comment]
Yep exactly. I think you can whisper in the thread and then only they can
see it

**Comment by andybaumgar** [comment]
Merged to try and demonstrate feature for review, but it doesn't work due to permissions.  There's still some quirks anyways, so I created a new issue https://github.com/nycmeshnet/nycmesh-support-bot/issues/50.
