### ISSUE TITLE
Suggest supportbot when message is posted

### ISSUE THREAD

**Issue by andybaumgar** [nycmeshnet/nycmesh-support-bot#50]

**Comment by andybaumgar** [comment]
May be able to use "conversations" api methods to detect first message in thread.

**Comment by andybaumgar** [comment]
Actually can just use timestamps.  Added in latest commit.

**Comment by andybaumgar** [comment]
We can probably use the [user list](https://api.slack.com/reference/block-kit/block-elements#users_multi_select) block to manually add people to @.

**Comment by Andrew-Dickinson** [comment]
Is the idea to @ the member or a support volunteer?

**Comment by andybaumgar** [comment]
Marg wanted it to @ a member.  I'm not sure if it's worth it since this would happen infrequently and it's easy to just @ them manually.  Thought I'd at least look into it.  It's also not really relevant to this auto running feature.
