### ISSUE TITLE
File timestamps are in UTC

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/nycmesh-support-bot#57]
When supportbot uploads the diagnostics report, it includes a timestamp. The server is likely set to UTC time zone, so by default the timestamps are offset from NYC time. We should convert the timestamp in python to be NYC local time so volunteers don't have to convert

**Comment by andybaumgar** [comment]
Sounds good, those should be a standard regex.  I think moving some of the script steps into python will be easier to maintain too.  It's difficult for me to debug and test the .sh.
