### ISSUE TITLE
Brake up nn_stats.sh into smaller scripts

### ISSUE THREAD

**Issue by andybaumgar** [nycmeshnet/nycmesh-support-bot#63]
I'm in the process of implementing https://github.com/nycmeshnet/nycmesh-support-bot/issues/61, but it's difficult to collapse the multiple traceroute outputs using shell scripts, so I'm planning on braking the large command into pieces I can test and modify with Python.

**Comment by Andrew-Dickinson** [comment]
👍

**Comment by andybaumgar** [comment]
I didn't end up needing to doing this yet.  It would be nice to be able to do unit tests quickly for individual commands though.  I think we'd have to run them on Docker somehow.  Maybe I could bundle that with setting up a fully containerized dev environment (currently I just use Docker to test the build, but use local Python for actual dev).

**Comment by andybaumgar** [comment]
Update: we do the UISP call in pure Python in the analytics code now, so that should be easy to port over.

**Comment by andybaumgar** [comment]
Process:
- pull UISP devices every so often (could be on a scheduled restart ever night)
- Create nn indexed devices list based on device name (already done in analysis scripts)
- after validating install nn check if nn exists in device list.  If not state nn does not have device

This will not work for Grand Street building numbers, but we could simply state that in the prompt if we want.
