### ISSUE TITLE
Bug: Bot reports LBE online when is offline

### ISSUE THREAD

**Issue by wilkcom** [nycmeshnet/nycmesh-support-bot#72]
This bug comes from ubiquiti. The AP will report good connection with the client even when is disconnected.
Suggestion: grab IP of LBE from Omni and ping it.

**Comment by andybaumgar** [comment]
Thanks for reporting this.  Is there an example you could link to on Slack?

**Comment by wilkcom** [comment]
here is example
https://nycmesh.slack.com/archives/C679UKBUK/p1676515365757849

**Comment by andybaumgar** [comment]
Thanks!

**Comment by andybaumgar** [comment]
Duplicate of https://github.com/nycmeshnet/nycmesh-support-bot/issues/73

**Comment by andybaumgar** [comment]
@wilkcom We are discussing this issue more in https://github.com/nycmeshnet/nycmesh-support-bot/issues/73.  The UISP data can be old, so we are going to add a disclaimer and show the last update time.
