### ISSUE TITLE
Add disclaimer about old / inaccurate UISP results 

### ISSUE THREAD

**Issue by andybaumgar** [nycmeshnet/nycmesh-support-bot#73]
LBE throughput data in particular can be old and confusing.

**Comment by andybaumgar** [comment]
“UISP stats are based on link potential, actual speeds may vary based on network conditions, weather, traffic patterns, etc. Use the Omni Speedtest results above (if present) for a more accurate representation of actual throughput”

**Comment by Andrew-Dickinson** [comment]
Also "last updated" label :)

**Comment by andybaumgar** [comment]
@danielhmetro Since you were working on the UISP python script.

**Comment by andybaumgar** [comment]
We may want to treat SXT-only installs the same as LBE-only installs.  The old/current? config assigns IPs like http://10.69.4.186/.

**Comment by Andrew-Dickinson** [comment]
Well in theory with the SXT we can remote in and do speed test/traceroute,
right? So imo it would ideally be more like omni-only than LBE only

**Comment by andybaumgar** [comment]
@Andrew-Dickinson True, but I was referencing [this thread](https://nycmesh.slack.com/archives/C045QM9TDMZ/p1676945155050969).  Single SXT mostly do not follow the same 10.69 rule so it may make sense to just use a UISP IP lookup similar to LBE-only.  In that thread Olivier was saying we should possibly even not give it a /26 since there's only one path.  Many of the SXT-only installs already have a 10.96 in addition to a 10.69 that both route to the same SXT device.

**Comment by Andrew-Dickinson** [comment]
Ah okay yes that makes sense. For IP lookup it's more like an LBE-only, but for data collection it's more like an Omni-only

**Comment by andybaumgar** [comment]
This issue was solved by #81, so I'm going to close it.
